name: future

on:
  push:
    branches:
      - main
  schedule:
    - cron: '24 4 * * FRI'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  run-script:
    strategy:
      matrix: {python: ['3.8','3.12','3.x']}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python || '3.x' }}
          cache: 'pip'


      - run: python app.py
      - name: Commit results
        run: |
          git diff --quiet || {
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add -A
            git commit -m 'Automation update'
            git push
          }
