name: Run User Script
on:
  workflow_dispatch:
    inputs:
      filepath:
        description: 'Path to script to execute'
        required: true
      install_requirements:
        description: 'Install from requirements.txt'
        required: false
        default: 'false'

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirements
        if: ${{ github.event.inputs.install_requirements == 'true' }}
        run: |
          pip install -r requirements.txt
      - name: Execute script
        run: python "${{ github.event.inputs.filepath }}"
