name: Run Scraping Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5 * * 6'
    - cron: '40 5 * * 6'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  run-script:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python main.py
      - name: Commit results
        run: |
          git diff --quiet || {
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add -A
            git commit -m 'Automation update'
            git push
          }
