name: Run Scraping Automation

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python (starter.py)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run starter.py
        run: python starter.py
      - name: Commit results
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add -A
            git commit -m 'Automation update'
            git push
          fi
